// @ts-nocheck
function stryNS_9fa48() {
  var g = typeof globalThis === 'object' && globalThis && globalThis.Math === Math && globalThis || new Function("return this")();
  var ns = g.__stryker__ || (g.__stryker__ = {});
  if (ns.activeMutant === undefined && g.process && g.process.env && g.process.env.__STRYKER_ACTIVE_MUTANT__) {
    ns.activeMutant = g.process.env.__STRYKER_ACTIVE_MUTANT__;
  }
  function retrieveNS() {
    return ns;
  }
  stryNS_9fa48 = retrieveNS;
  return retrieveNS();
}
stryNS_9fa48();
function stryCov_9fa48() {
  var ns = stryNS_9fa48();
  var cov = ns.mutantCoverage || (ns.mutantCoverage = {
    static: {},
    perTest: {}
  });
  function cover() {
    var c = cov.static;
    if (ns.currentTestId) {
      c = cov.perTest[ns.currentTestId] = cov.perTest[ns.currentTestId] || {};
    }
    var a = arguments;
    for (var i = 0; i < a.length; i++) {
      c[a[i]] = (c[a[i]] || 0) + 1;
    }
  }
  stryCov_9fa48 = cover;
  cover.apply(null, arguments);
}
function stryMutAct_9fa48(id) {
  var ns = stryNS_9fa48();
  function isActive(id) {
    if (ns.activeMutant === id) {
      if (ns.hitCount !== void 0 && ++ns.hitCount > ns.hitLimit) {
        throw new Error('Stryker: Hit count limit reached (' + ns.hitCount + ')');
      }
      return true;
    }
    return false;
  }
  stryMutAct_9fa48 = isActive;
  return isActive(id);
}
import db from '../config/db.js';
class AnalyticsRepository {
  /**
   * Log a learning event
   */
  async logEvent(userId, eventType, languageName, moduleType, duration = null, metadata = {}) {
    if (stryMutAct_9fa48("2138")) {
      {}
    } else {
      stryCov_9fa48("2138");
      try {
        if (stryMutAct_9fa48("2139")) {
          {}
        } else {
          stryCov_9fa48("2139");
          const query = stryMutAct_9fa48("2140") ? `` : (stryCov_9fa48("2140"), `
        INSERT INTO learning_logs (user_id, event_type, language_name, module_type, duration_seconds, metadata)
        VALUES ($1, $2, $3, $4, $5, $6);
      `);
          await db.query(query, stryMutAct_9fa48("2141") ? [] : (stryCov_9fa48("2141"), [userId, eventType, languageName, moduleType, duration, JSON.stringify(metadata)]));
          return stryMutAct_9fa48("2142") ? false : (stryCov_9fa48("2142"), true);
        }
      } catch (error) {
        if (stryMutAct_9fa48("2143")) {
          {}
        } else {
          stryCov_9fa48("2143");
          console.error(stryMutAct_9fa48("2144") ? "" : (stryCov_9fa48("2144"), 'Error logging analytics event:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get language distribution (languages with generated courses)
   * Shows all languages where courses have been generated by users
   */
  async getLanguageDistribution() {
    if (stryMutAct_9fa48("2145")) {
      {}
    } else {
      stryCov_9fa48("2145");
      try {
        if (stryMutAct_9fa48("2146")) {
          {}
        } else {
          stryCov_9fa48("2146");
          const query = stryMutAct_9fa48("2147") ? `` : (stryCov_9fa48("2147"), `
        SELECT 
          c.language as language_name,
          COUNT(DISTINCT c.id)::int as count
        FROM courses c
        WHERE c.language IS NOT NULL
          AND TRIM(c.language) <> ''
        GROUP BY c.language
        
        UNION ALL
        
        SELECT 
          lm.language as language_name,
          COUNT(DISTINCT lm.id)::int as count
        FROM language_modules lm
        WHERE lm.language IS NOT NULL
          AND TRIM(lm.language) <> ''
        GROUP BY lm.language
        
        ORDER BY count DESC;
      `);
          const result = await db.query(query);

          // Aggregate duplicate languages
          const aggregated = {};
          result.rows.forEach(row => {
            if (stryMutAct_9fa48("2148")) {
              {}
            } else {
              stryCov_9fa48("2148");
              if (stryMutAct_9fa48("2150") ? false : stryMutAct_9fa48("2149") ? true : (stryCov_9fa48("2149", "2150"), aggregated[row.language_name])) {
                if (stryMutAct_9fa48("2151")) {
                  {}
                } else {
                  stryCov_9fa48("2151");
                  stryMutAct_9fa48("2152") ? aggregated[row.language_name] -= row.count : (stryCov_9fa48("2152"), aggregated[row.language_name] += row.count);
                }
              } else {
                if (stryMutAct_9fa48("2153")) {
                  {}
                } else {
                  stryCov_9fa48("2153");
                  aggregated[row.language_name] = row.count;
                }
              }
            }
          });
          return stryMutAct_9fa48("2154") ? Object.entries(aggregated).map(([language_name, count]) => ({
            language_name,
            count
          })) : (stryCov_9fa48("2154"), Object.entries(aggregated).map(stryMutAct_9fa48("2155") ? () => undefined : (stryCov_9fa48("2155"), ([language_name, count]) => stryMutAct_9fa48("2156") ? {} : (stryCov_9fa48("2156"), {
            language_name,
            count
          }))).sort(stryMutAct_9fa48("2157") ? () => undefined : (stryCov_9fa48("2157"), (a, b) => stryMutAct_9fa48("2158") ? b.count + a.count : (stryCov_9fa48("2158"), b.count - a.count))));
        }
      } catch (error) {
        if (stryMutAct_9fa48("2159")) {
          {}
        } else {
          stryCov_9fa48("2159");
          console.error(stryMutAct_9fa48("2160") ? "" : (stryCov_9fa48("2160"), 'Error getting language distribution:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get module usage statistics (Admin vs AI)
   */
  async getModuleUsage() {
    if (stryMutAct_9fa48("2161")) {
      {}
    } else {
      stryCov_9fa48("2161");
      try {
        if (stryMutAct_9fa48("2162")) {
          {}
        } else {
          stryCov_9fa48("2162");
          const query = stryMutAct_9fa48("2163") ? `` : (stryCov_9fa48("2163"), `
        SELECT 
          module_type,
          COUNT(*) as count
        FROM learning_logs
        WHERE event_type = 'LESSON_COMPLETED'
        GROUP BY module_type
        ORDER BY count DESC;
      `);
          const result = await db.query(query);
          return result.rows;
        }
      } catch (error) {
        if (stryMutAct_9fa48("2164")) {
          {}
        } else {
          stryCov_9fa48("2164");
          console.error(stryMutAct_9fa48("2165") ? "" : (stryCov_9fa48("2165"), 'Error getting module usage:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get AI performance metrics
   */
  async getAIPerformance() {
    if (stryMutAct_9fa48("2166")) {
      {}
    } else {
      stryCov_9fa48("2166");
      try {
        if (stryMutAct_9fa48("2167")) {
          {}
        } else {
          stryCov_9fa48("2167");
          const query = stryMutAct_9fa48("2168") ? `` : (stryCov_9fa48("2168"), `
        SELECT
          COUNT(*) as total_generations,
          SUM(CASE WHEN metadata->>'success' = 'true' THEN 1 ELSE 0 END) as success_count,
          SUM(CASE WHEN metadata->>'success' = 'false' THEN 1 ELSE 0 END) as failure_count
        FROM learning_logs
        WHERE event_type = 'AI_MODULE_GENERATED';
      `);
          const result = await db.query(query);
          return stryMutAct_9fa48("2171") ? result.rows[0] && {
            total_generations: 0,
            success_count: 0,
            failure_count: 0
          } : stryMutAct_9fa48("2170") ? false : stryMutAct_9fa48("2169") ? true : (stryCov_9fa48("2169", "2170", "2171"), result.rows[0] || (stryMutAct_9fa48("2172") ? {} : (stryCov_9fa48("2172"), {
            total_generations: 0,
            success_count: 0,
            failure_count: 0
          })));
        }
      } catch (error) {
        if (stryMutAct_9fa48("2173")) {
          {}
        } else {
          stryCov_9fa48("2173");
          console.error(stryMutAct_9fa48("2174") ? "" : (stryCov_9fa48("2174"), 'Error getting AI performance:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get daily activity statistics
   * FIX: Use parameterized query to prevent SQL injection
   */
  async getDailyActivity(days = 30) {
    if (stryMutAct_9fa48("2175")) {
      {}
    } else {
      stryCov_9fa48("2175");
      try {
        if (stryMutAct_9fa48("2176")) {
          {}
        } else {
          stryCov_9fa48("2176");
          // Ensure days is a valid integer
          const daysInt = stryMutAct_9fa48("2179") ? parseInt(days, 10) && 30 : stryMutAct_9fa48("2178") ? false : stryMutAct_9fa48("2177") ? true : (stryCov_9fa48("2177", "2178", "2179"), parseInt(days, 10) || 30);
          const query = stryMutAct_9fa48("2180") ? `` : (stryCov_9fa48("2180"), `
        SELECT 
          DATE(created_at) as date,
          COUNT(*) as total_activities,
          COUNT(DISTINCT user_id) as active_users
        FROM learning_logs
        WHERE created_at >= NOW() - INTERVAL '1 day' * $1
        GROUP BY DATE(created_at)
        ORDER BY date DESC;
      `);
          const result = await db.query(query, stryMutAct_9fa48("2181") ? [] : (stryCov_9fa48("2181"), [daysInt]));
          return result.rows;
        }
      } catch (error) {
        if (stryMutAct_9fa48("2182")) {
          {}
        } else {
          stryCov_9fa48("2182");
          console.error(stryMutAct_9fa48("2183") ? "" : (stryCov_9fa48("2183"), 'Error getting daily activity:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get user engagement metrics
   */
  async getUserEngagement() {
    if (stryMutAct_9fa48("2184")) {
      {}
    } else {
      stryCov_9fa48("2184");
      try {
        if (stryMutAct_9fa48("2185")) {
          {}
        } else {
          stryCov_9fa48("2185");
          const query = stryMutAct_9fa48("2186") ? `` : (stryCov_9fa48("2186"), `
        SELECT 
          COUNT(DISTINCT user_id) as total_active_users,
          AVG(daily_lessons) as avg_lessons_per_user,
          MAX(daily_lessons) as max_lessons_per_user
        FROM (
          SELECT 
            user_id,
            DATE(created_at) as date,
            COUNT(*) as daily_lessons
          FROM learning_logs
          WHERE event_type = 'LESSON_COMPLETED'
            AND created_at >= NOW() - INTERVAL '30 days'
          GROUP BY user_id, DATE(created_at)
        ) user_daily_stats;
      `);
          const result = await db.query(query);
          return stryMutAct_9fa48("2189") ? result.rows[0] && {
            total_active_users: 0,
            avg_lessons_per_user: 0,
            max_lessons_per_user: 0
          } : stryMutAct_9fa48("2188") ? false : stryMutAct_9fa48("2187") ? true : (stryCov_9fa48("2187", "2188", "2189"), result.rows[0] || (stryMutAct_9fa48("2190") ? {} : (stryCov_9fa48("2190"), {
            total_active_users: 0,
            avg_lessons_per_user: 0,
            max_lessons_per_user: 0
          })));
        }
      } catch (error) {
        if (stryMutAct_9fa48("2191")) {
          {}
        } else {
          stryCov_9fa48("2191");
          console.error(stryMutAct_9fa48("2192") ? "" : (stryCov_9fa48("2192"), 'Error getting user engagement:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get lesson completion trends over time
   * FIX: Use parameterized query to prevent SQL injection
   */
  async getLessonCompletionTrends(days = 30) {
    if (stryMutAct_9fa48("2193")) {
      {}
    } else {
      stryCov_9fa48("2193");
      try {
        if (stryMutAct_9fa48("2194")) {
          {}
        } else {
          stryCov_9fa48("2194");
          // Ensure days is a valid integer
          const daysInt = stryMutAct_9fa48("2197") ? parseInt(days, 10) && 30 : stryMutAct_9fa48("2196") ? false : stryMutAct_9fa48("2195") ? true : (stryCov_9fa48("2195", "2196", "2197"), parseInt(days, 10) || 30);
          const query = stryMutAct_9fa48("2198") ? `` : (stryCov_9fa48("2198"), `
        SELECT 
          DATE(created_at) as date,
          module_type,
          COUNT(*) as completions
        FROM learning_logs
        WHERE event_type = 'LESSON_COMPLETED'
          AND created_at >= NOW() - INTERVAL '1 day' * $1
        GROUP BY DATE(created_at), module_type
        ORDER BY date DESC, module_type;
      `);
          const result = await db.query(query, stryMutAct_9fa48("2199") ? [] : (stryCov_9fa48("2199"), [daysInt]));
          return result.rows;
        }
      } catch (error) {
        if (stryMutAct_9fa48("2200")) {
          {}
        } else {
          stryCov_9fa48("2200");
          console.error(stryMutAct_9fa48("2201") ? "" : (stryCov_9fa48("2201"), 'Error getting lesson completion trends:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get average lesson duration by module type
   */
  async getAverageLessonDuration() {
    if (stryMutAct_9fa48("2202")) {
      {}
    } else {
      stryCov_9fa48("2202");
      try {
        if (stryMutAct_9fa48("2203")) {
          {}
        } else {
          stryCov_9fa48("2203");
          const query = stryMutAct_9fa48("2204") ? `` : (stryCov_9fa48("2204"), `
        SELECT 
          module_type,
          language_name,
          AVG(duration_seconds) as avg_duration_seconds,
          COUNT(*) as total_lessons
        FROM learning_logs
        WHERE event_type = 'LESSON_COMPLETED'
          AND duration_seconds IS NOT NULL
        GROUP BY module_type, language_name
        ORDER BY module_type, language_name;
      `);
          const result = await db.query(query);
          return result.rows;
        }
      } catch (error) {
        if (stryMutAct_9fa48("2205")) {
          {}
        } else {
          stryCov_9fa48("2205");
          console.error(stryMutAct_9fa48("2206") ? "" : (stryCov_9fa48("2206"), 'Error getting average lesson duration:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get real-time platform statistics from database tables
   * FIX: Direct queries to actual tables for accurate real-time data
   */
  async getRealTimeStats() {
    if (stryMutAct_9fa48("2207")) {
      {}
    } else {
      stryCov_9fa48("2207");
      try {
        if (stryMutAct_9fa48("2208")) {
          {}
        } else {
          stryCov_9fa48("2208");
          const query = stryMutAct_9fa48("2209") ? `` : (stryCov_9fa48("2209"), `
        SELECT 
          -- Total lessons completed across all users
          (SELECT COUNT(*) FROM lesson_progress WHERE is_completed = true)::int as total_lessons,
          
          -- Active users (users who completed at least one lesson)
          (SELECT COUNT(DISTINCT learner_id) FROM lesson_progress WHERE is_completed = true)::int as active_users,
          
          -- Most popular language
          (
            SELECT c.language 
            FROM lesson_progress lp
            INNER JOIN courses c ON lp.course_id = c.id
            WHERE lp.is_completed = true
            GROUP BY c.language
            ORDER BY COUNT(*) DESC
            LIMIT 1
          ) as popular_language,
          
          -- AI generation stats
          (SELECT COUNT(*) FROM courses WHERE generation_duration_seconds IS NOT NULL)::int as ai_courses_generated,
          (SELECT AVG(generation_duration_seconds) FROM courses WHERE generation_duration_seconds IS NOT NULL)::int as avg_generation_time,
          
          -- Total XP earned
          (SELECT COALESCE(SUM(xp_earned), 0) FROM lesson_progress WHERE is_completed = true)::int as total_xp_earned;
      `);
          const result = await db.query(query);
          return stryMutAct_9fa48("2212") ? result.rows[0] && {
            total_lessons: 0,
            active_users: 0,
            popular_language: 'N/A',
            ai_courses_generated: 0,
            avg_generation_time: 0,
            total_xp_earned: 0
          } : stryMutAct_9fa48("2211") ? false : stryMutAct_9fa48("2210") ? true : (stryCov_9fa48("2210", "2211", "2212"), result.rows[0] || (stryMutAct_9fa48("2213") ? {} : (stryCov_9fa48("2213"), {
            total_lessons: 0,
            active_users: 0,
            popular_language: stryMutAct_9fa48("2214") ? "" : (stryCov_9fa48("2214"), 'N/A'),
            ai_courses_generated: 0,
            avg_generation_time: 0,
            total_xp_earned: 0
          })));
        }
      } catch (error) {
        if (stryMutAct_9fa48("2215")) {
          {}
        } else {
          stryCov_9fa48("2215");
          console.error(stryMutAct_9fa48("2216") ? "" : (stryCov_9fa48("2216"), 'Error getting real-time stats:'), error);
          throw error;
        }
      }
    }
  }
}
export default new AnalyticsRepository();