// @ts-nocheck
function stryNS_9fa48() {
  var g = typeof globalThis === 'object' && globalThis && globalThis.Math === Math && globalThis || new Function("return this")();
  var ns = g.__stryker__ || (g.__stryker__ = {});
  if (ns.activeMutant === undefined && g.process && g.process.env && g.process.env.__STRYKER_ACTIVE_MUTANT__) {
    ns.activeMutant = g.process.env.__STRYKER_ACTIVE_MUTANT__;
  }
  function retrieveNS() {
    return ns;
  }
  stryNS_9fa48 = retrieveNS;
  return retrieveNS();
}
stryNS_9fa48();
function stryCov_9fa48() {
  var ns = stryNS_9fa48();
  var cov = ns.mutantCoverage || (ns.mutantCoverage = {
    static: {},
    perTest: {}
  });
  function cover() {
    var c = cov.static;
    if (ns.currentTestId) {
      c = cov.perTest[ns.currentTestId] = cov.perTest[ns.currentTestId] || {};
    }
    var a = arguments;
    for (var i = 0; i < a.length; i++) {
      c[a[i]] = (c[a[i]] || 0) + 1;
    }
  }
  stryCov_9fa48 = cover;
  cover.apply(null, arguments);
}
function stryMutAct_9fa48(id) {
  var ns = stryNS_9fa48();
  function isActive(id) {
    if (ns.activeMutant === id) {
      if (ns.hitCount !== void 0 && ++ns.hitCount > ns.hitLimit) {
        throw new Error('Stryker: Hit count limit reached (' + ns.hitCount + ')');
      }
      return true;
    }
    return false;
  }
  stryMutAct_9fa48 = isActive;
  return isActive(id);
}
import db from '../config/db.js';
class AnalyticsRepository {
  /**
   * Log a learning event
   */
  async logEvent(userId, eventType, languageName, moduleType, duration = null, metadata = {}) {
    if (stryMutAct_9fa48("1978")) {
      {}
    } else {
      stryCov_9fa48("1978");
      try {
        if (stryMutAct_9fa48("1979")) {
          {}
        } else {
          stryCov_9fa48("1979");
          const query = stryMutAct_9fa48("1980") ? `` : (stryCov_9fa48("1980"), `
        INSERT INTO learning_logs (user_id, event_type, language_name, module_type, duration_seconds, metadata)
        VALUES ($1, $2, $3, $4, $5, $6);
      `);
          await db.query(query, stryMutAct_9fa48("1981") ? [] : (stryCov_9fa48("1981"), [userId, eventType, languageName, moduleType, duration, JSON.stringify(metadata)]));
          return stryMutAct_9fa48("1982") ? false : (stryCov_9fa48("1982"), true);
        }
      } catch (error) {
        if (stryMutAct_9fa48("1983")) {
          {}
        } else {
          stryCov_9fa48("1983");
          console.error(stryMutAct_9fa48("1984") ? "" : (stryCov_9fa48("1984"), 'Error logging analytics event:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get language distribution (languages with generated courses)
   * Shows all languages where courses have been generated by users
   */
  async getLanguageDistribution() {
    if (stryMutAct_9fa48("1985")) {
      {}
    } else {
      stryCov_9fa48("1985");
      try {
        if (stryMutAct_9fa48("1986")) {
          {}
        } else {
          stryCov_9fa48("1986");
          const query = stryMutAct_9fa48("1987") ? `` : (stryCov_9fa48("1987"), `
        SELECT 
          c.language as language_name,
          COUNT(DISTINCT c.id)::int as count
        FROM courses c
        WHERE c.language IS NOT NULL
          AND TRIM(c.language) <> ''
        GROUP BY c.language
        
        UNION ALL
        
        SELECT 
          lm.language as language_name,
          COUNT(DISTINCT lm.id)::int as count
        FROM language_modules lm
        WHERE lm.language IS NOT NULL
          AND TRIM(lm.language) <> ''
        GROUP BY lm.language
        
        ORDER BY count DESC;
      `);
          const result = await db.query(query);

          // Aggregate duplicate languages
          const aggregated = {};
          result.rows.forEach(row => {
            if (stryMutAct_9fa48("1988")) {
              {}
            } else {
              stryCov_9fa48("1988");
              if (stryMutAct_9fa48("1990") ? false : stryMutAct_9fa48("1989") ? true : (stryCov_9fa48("1989", "1990"), aggregated[row.language_name])) {
                if (stryMutAct_9fa48("1991")) {
                  {}
                } else {
                  stryCov_9fa48("1991");
                  stryMutAct_9fa48("1992") ? aggregated[row.language_name] -= row.count : (stryCov_9fa48("1992"), aggregated[row.language_name] += row.count);
                }
              } else {
                if (stryMutAct_9fa48("1993")) {
                  {}
                } else {
                  stryCov_9fa48("1993");
                  aggregated[row.language_name] = row.count;
                }
              }
            }
          });
          return stryMutAct_9fa48("1994") ? Object.entries(aggregated).map(([language_name, count]) => ({
            language_name,
            count
          })) : (stryCov_9fa48("1994"), Object.entries(aggregated).map(stryMutAct_9fa48("1995") ? () => undefined : (stryCov_9fa48("1995"), ([language_name, count]) => stryMutAct_9fa48("1996") ? {} : (stryCov_9fa48("1996"), {
            language_name,
            count
          }))).sort(stryMutAct_9fa48("1997") ? () => undefined : (stryCov_9fa48("1997"), (a, b) => stryMutAct_9fa48("1998") ? b.count + a.count : (stryCov_9fa48("1998"), b.count - a.count))));
        }
      } catch (error) {
        if (stryMutAct_9fa48("1999")) {
          {}
        } else {
          stryCov_9fa48("1999");
          console.error(stryMutAct_9fa48("2000") ? "" : (stryCov_9fa48("2000"), 'Error getting language distribution:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get module usage statistics (Admin vs AI)
   */
  async getModuleUsage() {
    if (stryMutAct_9fa48("2001")) {
      {}
    } else {
      stryCov_9fa48("2001");
      try {
        if (stryMutAct_9fa48("2002")) {
          {}
        } else {
          stryCov_9fa48("2002");
          const query = stryMutAct_9fa48("2003") ? `` : (stryCov_9fa48("2003"), `
        SELECT 
          module_type,
          COUNT(*) as count
        FROM learning_logs
        WHERE event_type = 'LESSON_COMPLETED'
        GROUP BY module_type
        ORDER BY count DESC;
      `);
          const result = await db.query(query);
          return result.rows;
        }
      } catch (error) {
        if (stryMutAct_9fa48("2004")) {
          {}
        } else {
          stryCov_9fa48("2004");
          console.error(stryMutAct_9fa48("2005") ? "" : (stryCov_9fa48("2005"), 'Error getting module usage:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get AI performance metrics
   */
  async getAIPerformance() {
    if (stryMutAct_9fa48("2006")) {
      {}
    } else {
      stryCov_9fa48("2006");
      try {
        if (stryMutAct_9fa48("2007")) {
          {}
        } else {
          stryCov_9fa48("2007");
          const query = stryMutAct_9fa48("2008") ? `` : (stryCov_9fa48("2008"), `
        SELECT
          COUNT(*) as total_generations,
          SUM(CASE WHEN metadata->>'success' = 'true' THEN 1 ELSE 0 END) as success_count,
          SUM(CASE WHEN metadata->>'success' = 'false' THEN 1 ELSE 0 END) as failure_count
        FROM learning_logs
        WHERE event_type = 'AI_MODULE_GENERATED';
      `);
          const result = await db.query(query);
          return stryMutAct_9fa48("2011") ? result.rows[0] && {
            total_generations: 0,
            success_count: 0,
            failure_count: 0
          } : stryMutAct_9fa48("2010") ? false : stryMutAct_9fa48("2009") ? true : (stryCov_9fa48("2009", "2010", "2011"), result.rows[0] || (stryMutAct_9fa48("2012") ? {} : (stryCov_9fa48("2012"), {
            total_generations: 0,
            success_count: 0,
            failure_count: 0
          })));
        }
      } catch (error) {
        if (stryMutAct_9fa48("2013")) {
          {}
        } else {
          stryCov_9fa48("2013");
          console.error(stryMutAct_9fa48("2014") ? "" : (stryCov_9fa48("2014"), 'Error getting AI performance:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get daily activity statistics
   * FIX: Use parameterized query to prevent SQL injection
   */
  async getDailyActivity(days = 30) {
    if (stryMutAct_9fa48("2015")) {
      {}
    } else {
      stryCov_9fa48("2015");
      try {
        if (stryMutAct_9fa48("2016")) {
          {}
        } else {
          stryCov_9fa48("2016");
          // Ensure days is a valid integer
          const daysInt = stryMutAct_9fa48("2019") ? parseInt(days, 10) && 30 : stryMutAct_9fa48("2018") ? false : stryMutAct_9fa48("2017") ? true : (stryCov_9fa48("2017", "2018", "2019"), parseInt(days, 10) || 30);
          const query = stryMutAct_9fa48("2020") ? `` : (stryCov_9fa48("2020"), `
        SELECT 
          DATE(created_at) as date,
          COUNT(*) as total_activities,
          COUNT(DISTINCT user_id) as active_users
        FROM learning_logs
        WHERE created_at >= NOW() - INTERVAL '1 day' * $1
        GROUP BY DATE(created_at)
        ORDER BY date DESC;
      `);
          const result = await db.query(query, stryMutAct_9fa48("2021") ? [] : (stryCov_9fa48("2021"), [daysInt]));
          return result.rows;
        }
      } catch (error) {
        if (stryMutAct_9fa48("2022")) {
          {}
        } else {
          stryCov_9fa48("2022");
          console.error(stryMutAct_9fa48("2023") ? "" : (stryCov_9fa48("2023"), 'Error getting daily activity:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get user engagement metrics
   */
  async getUserEngagement() {
    if (stryMutAct_9fa48("2024")) {
      {}
    } else {
      stryCov_9fa48("2024");
      try {
        if (stryMutAct_9fa48("2025")) {
          {}
        } else {
          stryCov_9fa48("2025");
          const query = stryMutAct_9fa48("2026") ? `` : (stryCov_9fa48("2026"), `
        SELECT 
          COUNT(DISTINCT user_id) as total_active_users,
          AVG(daily_lessons) as avg_lessons_per_user,
          MAX(daily_lessons) as max_lessons_per_user
        FROM (
          SELECT 
            user_id,
            DATE(created_at) as date,
            COUNT(*) as daily_lessons
          FROM learning_logs
          WHERE event_type = 'LESSON_COMPLETED'
            AND created_at >= NOW() - INTERVAL '30 days'
          GROUP BY user_id, DATE(created_at)
        ) user_daily_stats;
      `);
          const result = await db.query(query);
          return stryMutAct_9fa48("2029") ? result.rows[0] && {
            total_active_users: 0,
            avg_lessons_per_user: 0,
            max_lessons_per_user: 0
          } : stryMutAct_9fa48("2028") ? false : stryMutAct_9fa48("2027") ? true : (stryCov_9fa48("2027", "2028", "2029"), result.rows[0] || (stryMutAct_9fa48("2030") ? {} : (stryCov_9fa48("2030"), {
            total_active_users: 0,
            avg_lessons_per_user: 0,
            max_lessons_per_user: 0
          })));
        }
      } catch (error) {
        if (stryMutAct_9fa48("2031")) {
          {}
        } else {
          stryCov_9fa48("2031");
          console.error(stryMutAct_9fa48("2032") ? "" : (stryCov_9fa48("2032"), 'Error getting user engagement:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get lesson completion trends over time
   * FIX: Use parameterized query to prevent SQL injection
   */
  async getLessonCompletionTrends(days = 30) {
    if (stryMutAct_9fa48("2033")) {
      {}
    } else {
      stryCov_9fa48("2033");
      try {
        if (stryMutAct_9fa48("2034")) {
          {}
        } else {
          stryCov_9fa48("2034");
          // Ensure days is a valid integer
          const daysInt = stryMutAct_9fa48("2037") ? parseInt(days, 10) && 30 : stryMutAct_9fa48("2036") ? false : stryMutAct_9fa48("2035") ? true : (stryCov_9fa48("2035", "2036", "2037"), parseInt(days, 10) || 30);
          const query = stryMutAct_9fa48("2038") ? `` : (stryCov_9fa48("2038"), `
        SELECT 
          DATE(created_at) as date,
          module_type,
          COUNT(*) as completions
        FROM learning_logs
        WHERE event_type = 'LESSON_COMPLETED'
          AND created_at >= NOW() - INTERVAL '1 day' * $1
        GROUP BY DATE(created_at), module_type
        ORDER BY date DESC, module_type;
      `);
          const result = await db.query(query, stryMutAct_9fa48("2039") ? [] : (stryCov_9fa48("2039"), [daysInt]));
          return result.rows;
        }
      } catch (error) {
        if (stryMutAct_9fa48("2040")) {
          {}
        } else {
          stryCov_9fa48("2040");
          console.error(stryMutAct_9fa48("2041") ? "" : (stryCov_9fa48("2041"), 'Error getting lesson completion trends:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get average lesson duration by module type
   */
  async getAverageLessonDuration() {
    if (stryMutAct_9fa48("2042")) {
      {}
    } else {
      stryCov_9fa48("2042");
      try {
        if (stryMutAct_9fa48("2043")) {
          {}
        } else {
          stryCov_9fa48("2043");
          const query = stryMutAct_9fa48("2044") ? `` : (stryCov_9fa48("2044"), `
        SELECT 
          module_type,
          language_name,
          AVG(duration_seconds) as avg_duration_seconds,
          COUNT(*) as total_lessons
        FROM learning_logs
        WHERE event_type = 'LESSON_COMPLETED'
          AND duration_seconds IS NOT NULL
        GROUP BY module_type, language_name
        ORDER BY module_type, language_name;
      `);
          const result = await db.query(query);
          return result.rows;
        }
      } catch (error) {
        if (stryMutAct_9fa48("2045")) {
          {}
        } else {
          stryCov_9fa48("2045");
          console.error(stryMutAct_9fa48("2046") ? "" : (stryCov_9fa48("2046"), 'Error getting average lesson duration:'), error);
          throw error;
        }
      }
    }
  }

  /**
   * Get real-time platform statistics from database tables
   * FIX: Direct queries to actual tables for accurate real-time data
   */
  async getRealTimeStats() {
    if (stryMutAct_9fa48("2047")) {
      {}
    } else {
      stryCov_9fa48("2047");
      try {
        if (stryMutAct_9fa48("2048")) {
          {}
        } else {
          stryCov_9fa48("2048");
          const query = stryMutAct_9fa48("2049") ? `` : (stryCov_9fa48("2049"), `
        SELECT 
          -- Total lessons completed across all users
          (SELECT COUNT(*) FROM lesson_progress WHERE is_completed = true)::int as total_lessons,
          
          -- Active users (users who completed at least one lesson)
          (SELECT COUNT(DISTINCT learner_id) FROM lesson_progress WHERE is_completed = true)::int as active_users,
          
          -- Most popular language
          (
            SELECT c.language 
            FROM lesson_progress lp
            INNER JOIN courses c ON lp.course_id = c.id
            WHERE lp.is_completed = true
            GROUP BY c.language
            ORDER BY COUNT(*) DESC
            LIMIT 1
          ) as popular_language,
          
          -- AI generation stats
          (SELECT COUNT(*) FROM courses WHERE generation_duration_seconds IS NOT NULL)::int as ai_courses_generated,
          (SELECT AVG(generation_duration_seconds) FROM courses WHERE generation_duration_seconds IS NOT NULL)::int as avg_generation_time,
          
          -- Total XP earned
          (SELECT COALESCE(SUM(xp_earned), 0) FROM lesson_progress WHERE is_completed = true)::int as total_xp_earned;
      `);
          const result = await db.query(query);
          return stryMutAct_9fa48("2052") ? result.rows[0] && {
            total_lessons: 0,
            active_users: 0,
            popular_language: 'N/A',
            ai_courses_generated: 0,
            avg_generation_time: 0,
            total_xp_earned: 0
          } : stryMutAct_9fa48("2051") ? false : stryMutAct_9fa48("2050") ? true : (stryCov_9fa48("2050", "2051", "2052"), result.rows[0] || (stryMutAct_9fa48("2053") ? {} : (stryCov_9fa48("2053"), {
            total_lessons: 0,
            active_users: 0,
            popular_language: stryMutAct_9fa48("2054") ? "" : (stryCov_9fa48("2054"), 'N/A'),
            ai_courses_generated: 0,
            avg_generation_time: 0,
            total_xp_earned: 0
          })));
        }
      } catch (error) {
        if (stryMutAct_9fa48("2055")) {
          {}
        } else {
          stryCov_9fa48("2055");
          console.error(stryMutAct_9fa48("2056") ? "" : (stryCov_9fa48("2056"), 'Error getting real-time stats:'), error);
          throw error;
        }
      }
    }
  }
}
export default new AnalyticsRepository();